services:
  - type: web
    name: cafe-backend
    runtime: docker
    plan: free
    region: oregon
    dockerContext: ./backend-laravel
    dockerfilePath: ./backend-laravel/Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: CafeOps Suite
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cafe-backend-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cafe-backend-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cafe-backend-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cafe-backend-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cafe-backend-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: "true"

databases:
  - name: cafe-backend-db
    databaseName: cafe_manager
    user: cafe_manager
    plan: free
