services:
  - type: web
    name: cafe-backend
    runtime: docker
    plan: free
    region: oregon
    dockerContext: ./backend-laravel
    dockerfilePath: ./backend-laravel/Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: CafeOps Suite
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://all-in-one-business-manager-for-small.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: "true"
